config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  
  resources "entries"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @entries = Entry.all
  end 

  def show
    @entry = Entry.find(params["id"])
    p params
  end 

  def create
  entry_params = params["entry"].permit("title", "contents")
  entry = Entry.create(entry_params)
  redirect_to(entry_path(entry))
  end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @entries = Entry.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/index.html.erb
<h2><%= link_to(entry.title, entry_path(entry)) %></h2>

<%= link_to("New entry", new_entry_path) %>

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<%= @entry.title %></h2>

  <p><%= @entry.date %></p>
  
  <p><%= @entry.contents %></p>


  <p><%= link_to("Back to all entries", entries_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Diary</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>
  <body>
      <h1>Diary</h1>
      <div>
        <h2></h2>
          <% for entry in @entries %>
        <h2><%= entry.title %></h2>
       <p><%= entry.date %></p>
       <p><%= entry.contents %></p>
      <% end %>
      </div>
      <div>
          <h1>My favourite websites</h1>
            <ul>
              <li><a href="http://twitter.com">Twitter</a></li>
              <li><a href="https://instagram.com">Instagram</a></li>
              <li><a href="http://codewars.com">CodeWars</a></li>
            </ul>
          </div>
        
  </body>
</html>